import PublicShell from "../../components/public/PublicShell";
import { LegalSection, LegalList, LastUpdated } from "../../components/public/LegalDoc";

export const metadata = {
  title: "Privacy Policy",
  description: "How PeerSupport collects, uses, and protects your personal data.",
};

export default function PrivacyPolicyPage() {
  return (
    <PublicShell title="Privacy Policy" description="How we collect, use, and protect your information.">
      <LastUpdated date="20 September 2026" />

      <LegalSection first title="1. Who we are">
        <p>
          PeerSupport (&quot;PeerSupport&quot;, &quot;we&quot;, &quot;us&quot;, or &quot;our&quot;) operates a
          mentorship marketplace connecting mentees with mentors for 1-on-1
          sessions. This policy explains what personal data we collect when you
          use our website and app, why we collect it, and the choices you have.
        </p>
      </LegalSection>

      <LegalSection title="2. Information we collect">
        <p>We collect information you give us directly, information generated by using the platform, and information from third parties you choose to connect.</p>
        <LegalList
          items={[
            "Account information: name, email address, phone number, password (hashed), and profile photo — either uploaded by you or, if you sign up with Google, provided by your Google account.",
            "Mentor application details: education history, professional background, LinkedIn profile, expertise areas, mentoring responses, and verification documents (e.g. student ID, degree, marksheet) submitted during mentor onboarding.",
            "Booking and session data: session bookings, schedules, session notes, feedback and ratings you submit, and recordings or transcripts where a session format explicitly provides them.",
            "Payment information: transaction amounts, booking references, and payout details for mentors. Card and UPI details are processed directly by our payment processor — we do not store your full card number or bank credentials on our servers.",
            "Communications: messages sent through in-app support tickets, contact forms, and any correspondence with our team.",
            "Technical data: IP address, browser type, device information, and usage data collected via cookies and similar technologies (see our Cookie Policy).",
          ]}
        />
      </LegalSection>

      <LegalSection title="3. How we use your information">
        <LegalList
          items={[
            "To create and manage your account, and to match mentees with suitable mentors.",
            "To process bookings, facilitate live sessions (including generating secure video-session credentials), and send related reminders and notifications by email and SMS.",
            "To review and verify mentor applications, including scheduling verification calls via Google Calendar and video conferencing.",
            "To process payments to mentees and payouts to mentors, and to maintain records required for accounting and tax compliance.",
            "To respond to support requests and communicate important service updates.",
            "To maintain the safety, security, and integrity of the platform, including detecting fraud and misuse.",
            "To improve our services through aggregated, de-identified analysis of how the platform is used.",
          ]}
        />
      </LegalSection>

      <LegalSection title="4. How we share your information">
        <p>We do not sell your personal data. We share information only in the following circumstances:</p>
        <LegalList
          items={[
            "Between mentees and mentors as needed to facilitate a booked session (e.g. your name and profile are visible to the mentor/mentee you're booked with).",
            "With service providers who process data on our behalf — including cloud hosting, file storage (Cloudinary), video conferencing (Agora), email/SMS delivery, and payment processing — under contractual confidentiality obligations.",
            "With Google, solely to generate Google Calendar invites and Meet links when scheduling mentor verification calls.",
            "If required by law, regulation, legal process, or governmental request, or to protect the rights, property, or safety of PeerSupport, our users, or the public.",
            "In connection with a merger, acquisition, or sale of assets, subject to standard confidentiality arrangements.",
          ]}
        />
      </LegalSection>

      <LegalSection title="5. Data retention">
        <p>
          We retain personal data for as long as your account is active and as needed to provide
          our services, comply with legal obligations (including tax and financial record-keeping),
          resolve disputes, and enforce our agreements. You may request deletion of your account at
          any time, subject to the retention requirements described above.
        </p>
      </LegalSection>

      <LegalSection title="6. Your rights and choices">
        <LegalList
          items={[
            "Access and update most of your profile information directly from your account settings.",
            "Request a copy of the personal data we hold about you, or request that we correct or delete it, by contacting us at the email below.",
            "Opt out of promotional emails at any time using the unsubscribe link in those emails; you will still receive transactional messages related to your bookings and account.",
            "Control cookies through your browser settings — see our Cookie Policy for details.",
          ]}
        />
      </LegalSection>

      <LegalSection title="7. Data security">
        <p>
          We use industry-standard safeguards — including encrypted connections, hashed passwords,
          and access-controlled cloud storage — to protect your data. No method of transmission or
          storage is completely secure, and we cannot guarantee absolute security.
        </p>
      </LegalSection>

      <LegalSection title="8. Children's privacy">
        <p>
          PeerSupport is intended for users who are at least 18 years old, or who otherwise meet the
          minimum age of digital consent in their jurisdiction. We do not knowingly collect personal
          data from children below this age.
        </p>
      </LegalSection>

      <LegalSection title="9. Changes to this policy">
        <p>
          We may update this Privacy Policy from time to time. If we make material changes, we will
          notify you by email or through a notice on the platform before the changes take effect.
        </p>
      </LegalSection>

      <LegalSection title="10. Contact us">
        <p>
          Questions about this policy or your data? Reach us at{" "}
          <a href="mailto:hello@peersupport.in" className="font-semibold text-[#5061E4] hover:underline">
            hello@peersupport.in
          </a>.
        </p>
      </LegalSection>
    </PublicShell>
  );
}
